# Generated by Django 6.1 on 2026-08-09 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supabase_user_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('avatar_url', models.URLField(blank=True, max_length=1000)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('experience_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', max_length=20)),
                ('risk_tolerance', models.CharField(choices=[('CONSERVATIVE', 'Conservative'), ('MODERATE', 'Moderate'), ('AGGRESSIVE', 'Aggressive')], default='MODERATE', max_length=20)),
                ('investment_horizon', models.CharField(choices=[('SHORT_TERM', 'Short term'), ('MEDIUM_TERM', 'Medium term'), ('LONG_TERM', 'Long term')], default='LONG_TERM', max_length=20)),
                ('preferred_market', models.CharField(blank=True, max_length=80)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('auth_provider', models.CharField(blank=True, max_length=40)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
